version: '3'
services:
  web:
    build: ./geekspeak-web
    ports:
      - "8080:80"
      - "8081:81"
    volumes:
      - ./weblog:/var/log/nginx
    links:
      - db
    tty: false
  db:
    build: ./geekspeak-db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/pgdata
      - ./dblog:/var/log
    tty: true
volumes:
  weblog:
  dblog:
  pgdata:
